In [1]:
import pandas as pd
import os
import json

In [2]:
with open(f"all_table_files.json", "r", encoding="utf-8") as f:
    data = json.load(f)

In [ ]:
cik_list = [d['file_name'].split('.')[0] for d in data]

[{'folder_name': 'forms_table',
  'file_name': '0000107136.csv',
  'path_display': '/Nizar/forms_table/0000107136.csv',
  'size_bytes': 8665,
  'server_modified': '2026-01-31T14:52:30',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZvA'},
 {'folder_name': 'forms_table',
  'file_name': '0001114831.csv',
  'path_display': '/Nizar/forms_table/0001114831.csv',
  'size_bytes': 8691,
  'server_modified': '2026-01-31T14:55:06',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZvQ'},
 {'folder_name': 'forms_table',
  'file_name': '0001641761.csv',
  'path_display': '/Nizar/forms_table/0001641761.csv',
  'size_bytes': 2575,
  'server_modified': '2026-01-31T14:55:13',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZvg'},
 {'folder_name': 'forms_table',
  'file_name': '0001511144.csv',
  'path_display': '/Nizar/forms_table/0001511144.csv',
  'size_bytes': 9937,
  'server_modified': '2026-01-31T14:55:16',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZvw'},
 {'folder_name': 'forms_table',
  'file_name': '0001580250.csv',
  'path_display': '/Nizar/forms_table/0001580250.csv',
  'size_bytes': 751,
  'server_modified': '2026-01-31T14:55:20',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZwA'},
 {'folder_name': 'forms_table',
  'file_name': '0001602119.csv',
  'path_display': '/Nizar/forms_table/0001602119.csv',
  'size_bytes': 9959,
  'server_modified': '2026-01-31T14:55:27',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZwQ'},
 {'folder_name': 'forms_table',
  'file_name': '0002056650.csv',
  'path_display': '/Nizar/forms_table/0002056650.csv',
  'size_bytes': 1263,
  'server_modified': '2026-01-31T14:55:30',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZwg'},
 {'folder_name': 'forms_table',
  'file_name': '0001463262.csv',
  'path_display': '/Nizar/forms_table/0001463262.csv',
  'size_bytes': 1778,
  'server_modified': '2026-01-31T14:55:34',
  'id': 'id:q8Gozjz1MYAAAAAAAAgE_Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001801172.csv',
  'path_display': '/Nizar/forms_table/0001801172.csv',
  'size_bytes': 5911,
  'server_modified': '2026-01-31T14:55:37',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZww'},
 {'folder_name': 'forms_table',
  'file_name': '0002060412.csv',
  'path_display': '/Nizar/forms_table/0002060412.csv',
  'size_bytes': 1207,
  'server_modified': '2026-01-31T14:55:41',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZxA'},
 {'folder_name': 'forms_table',
  'file_name': '0001540531.csv',
  'path_display': '/Nizar/forms_table/0001540531.csv',
  'size_bytes': 14329,
  'server_modified': '2026-01-31T14:55:44',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZxQ'},
 {'folder_name': 'forms_table',
  'file_name': '0002011147.csv',
  'path_display': '/Nizar/forms_table/0002011147.csv',
  'size_bytes': 1637,
  'server_modified': '2026-01-31T14:55:48',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZxw'},
 {'folder_name': 'forms_table',
  'file_name': '0001633703.csv',
  'path_display': '/Nizar/forms_table/0001633703.csv',
  'size_bytes': 12241,
  'server_modified': '2026-01-31T14:55:53',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZyA'},
 {'folder_name': 'forms_table',
  'file_name': '0001230588.csv',
  'path_display': '/Nizar/forms_table/0001230588.csv',
  'size_bytes': 10713,
  'server_modified': '2026-01-31T14:55:57',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZyQ'},
 {'folder_name': 'forms_table',
  'file_name': '0001600133.csv',
  'path_display': '/Nizar/forms_table/0001600133.csv',
  'size_bytes': 13906,
  'server_modified': '2026-01-31T14:56:03',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZyg'},
 {'folder_name': 'forms_table',
  'file_name': '0001820788.csv',
  'path_display': '/Nizar/forms_table/0001820788.csv',
  'size_bytes': 5950,
  'server_modified': '2026-01-31T14:56:06',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZyw'},
 {'folder_name': 'forms_table',
  'file_name': '0001844084.csv',
  'path_display': '/Nizar/forms_table/0001844084.csv',
  'size_bytes': 6555,
  'server_modified': '2026-01-31T14:56:09',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZzA'},
 {'folder_name': 'forms_table',
  'file_name': '0001584087.csv',
  'path_display': '/Nizar/forms_table/0001584087.csv',
  'size_bytes': 14790,
  'server_modified': '2026-01-31T14:56:13',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZzQ'},
 {'folder_name': 'forms_table',
  'file_name': '0002009911.csv',
  'path_display': '/Nizar/forms_table/0002009911.csv',
  'size_bytes': 2289,
  'server_modified': '2026-01-31T14:56:16',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZzg'},
 {'folder_name': 'forms_table',
  'file_name': '0001436866.csv',
  'path_display': '/Nizar/forms_table/0001436866.csv',
  'size_bytes': 18818,
  'server_modified': '2026-01-31T14:56:19',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZzw'},
 {'folder_name': 'forms_table',
  'file_name': '0001811034.csv',
  'path_display': '/Nizar/forms_table/0001811034.csv',
  'size_bytes': 6236,
  'server_modified': '2026-01-31T14:56:26',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ0Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001727407.csv',
  'path_display': '/Nizar/forms_table/0001727407.csv',
  'size_bytes': 4007,
  'server_modified': '2026-01-31T14:56:29',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ0g'},
 {'folder_name': 'forms_table',
  'file_name': '0001625247.csv',
  'path_display': '/Nizar/forms_table/0001625247.csv',
  'size_bytes': 8978,
  'server_modified': '2026-01-31T14:56:33',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ0w'},
 {'folder_name': 'forms_table',
  'file_name': '0001803140.csv',
  'path_display': '/Nizar/forms_table/0001803140.csv',
  'size_bytes': 7401,
  'server_modified': '2026-01-31T14:56:36',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ1A'},
 {'folder_name': 'forms_table',
  'file_name': '0001427790.csv',
  'path_display': '/Nizar/forms_table/0001427790.csv',
  'size_bytes': 7939,
  'server_modified': '2026-01-31T14:56:39',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ1Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001730817.csv',
  'path_display': '/Nizar/forms_table/0001730817.csv',
  'size_bytes': 9790,
  'server_modified': '2026-01-31T14:56:42',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ1g'},
 {'folder_name': 'forms_table',
  'file_name': '0001633119.csv',
  'path_display': '/Nizar/forms_table/0001633119.csv',
  'size_bytes': 4399,
  'server_modified': '2026-01-31T14:56:46',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ1w'},
 {'folder_name': 'forms_table',
  'file_name': '0000944388.csv',
  'path_display': '/Nizar/forms_table/0000944388.csv',
  'size_bytes': 15811,
  'server_modified': '2026-01-31T14:56:49',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ2A'},
 {'folder_name': 'forms_table',
  'file_name': '0001138486.csv',
  'path_display': '/Nizar/forms_table/0001138486.csv',
  'size_bytes': 27383,
  'server_modified': '2026-01-31T14:56:53',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ2Q'},
 {'folder_name': 'forms_table',
  'file_name': '0000933996.csv',
  'path_display': '/Nizar/forms_table/0000933996.csv',
  'size_bytes': 1648,
  'server_modified': '2026-01-31T14:56:58',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ2w'},
 {'folder_name': 'forms_table',
  'file_name': '0001077487.csv',
  'path_display': '/Nizar/forms_table/0001077487.csv',
  'size_bytes': 7598,
  'server_modified': '2026-01-31T14:57:01',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ3A'},
 {'folder_name': 'forms_table',
  'file_name': '0002011812.csv',
  'path_display': '/Nizar/forms_table/0002011812.csv',
  'size_bytes': 2426,
  'server_modified': '2026-01-31T14:57:07',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ3Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001885092.csv',
  'path_display': '/Nizar/forms_table/0001885092.csv',
  'size_bytes': 4740,
  'server_modified': '2026-01-31T14:57:10',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ3g'},
 {'folder_name': 'forms_table',
  'file_name': '0001791996.csv',
  'path_display': '/Nizar/forms_table/0001791996.csv',
  'size_bytes': 6158,
  'server_modified': '2026-01-31T14:57:13',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ3w'},
 {'folder_name': 'forms_table',
  'file_name': '0001135986.csv',
  'path_display': '/Nizar/forms_table/0001135986.csv',
  'size_bytes': 27690,
  'server_modified': '2026-01-31T14:57:17',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ4A'},
 {'folder_name': 'forms_table',
  'file_name': '0001324943.csv',
  'path_display': '/Nizar/forms_table/0001324943.csv',
  'size_bytes': 22507,
  'server_modified': '2026-01-31T14:57:20',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ4Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001584289.csv',
  'path_display': '/Nizar/forms_table/0001584289.csv',
  'size_bytes': 16000,
  'server_modified': '2026-01-31T14:57:24',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ4g'},
 {'folder_name': 'forms_table',
  'file_name': '0001584304.csv',
  'path_display': '/Nizar/forms_table/0001584304.csv',
  'size_bytes': 14033,
  'server_modified': '2026-01-31T14:57:27',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ4w'},
 {'folder_name': 'forms_table',
  'file_name': '0001584306.csv',
  'path_display': '/Nizar/forms_table/0001584306.csv',
  'size_bytes': 14033,
  'server_modified': '2026-01-31T14:57:30',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ5A'},
 {'folder_name': 'forms_table',
  'file_name': '0001570769.csv',
  'path_display': '/Nizar/forms_table/0001570769.csv',
  'size_bytes': 13833,
  'server_modified': '2026-01-31T14:57:33',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ5Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001386792.csv',
  'path_display': '/Nizar/forms_table/0001386792.csv',
  'size_bytes': 14657,
  'server_modified': '2026-01-31T14:57:36',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ5g'},
 {'folder_name': 'forms_table',
  'file_name': '0001227807.csv',
  'path_display': '/Nizar/forms_table/0001227807.csv',
  'size_bytes': 6339,
  'server_modified': '2026-01-31T14:57:42',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ6A'},
 {'folder_name': 'forms_table',
  'file_name': '0001656866.csv',
  'path_display': '/Nizar/forms_table/0001656866.csv',
  'size_bytes': 2119,
  'server_modified': '2026-01-31T14:57:45',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ6Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001904262.csv',
  'path_display': '/Nizar/forms_table/0001904262.csv',
  'size_bytes': 2081,
  'server_modified': '2026-01-31T14:57:49',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ6w'},
 {'folder_name': 'forms_table',
  'file_name': '0001904235.csv',
  'path_display': '/Nizar/forms_table/0001904235.csv',
  'size_bytes': 2081,
  'server_modified': '2026-01-31T14:57:52',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ7A'},
 {'folder_name': 'forms_table',
  'file_name': '0002067541.csv',
  'path_display': '/Nizar/forms_table/0002067541.csv',
  'size_bytes': 1014,
  'server_modified': '2026-01-31T14:57:56',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ7Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001389112.csv',
  'path_display': '/Nizar/forms_table/0001389112.csv',
  'size_bytes': 1327,
  'server_modified': '2026-01-31T14:57:59',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ7g'},
 {'folder_name': 'forms_table',
  'file_name': '0001694297.csv',
  'path_display': '/Nizar/forms_table/0001694297.csv',
  'size_bytes': 9472,
  'server_modified': '2026-01-31T14:58:02',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ7w'},
 {'folder_name': 'forms_table',
  'file_name': '0001692205.csv',
  'path_display': '/Nizar/forms_table/0001692205.csv',
  'size_bytes': 3608,
  'server_modified': '2026-01-31T14:58:05',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ8A'},
 {'folder_name': 'forms_table',
  'file_name': '0001968777.csv',
  'path_display': '/Nizar/forms_table/0001968777.csv',
  'size_bytes': 3369,
  'server_modified': '2026-01-31T14:58:09',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ8Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001872224.csv',
  'path_display': '/Nizar/forms_table/0001872224.csv',
  'size_bytes': 4216,
  'server_modified': '2026-01-31T14:58:13',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ8g'},
 {'folder_name': 'forms_table',
  'file_name': '0001778867.csv',
  'path_display': '/Nizar/forms_table/0001778867.csv',
  'size_bytes': 1865,
  'server_modified': '2026-01-31T14:58:16',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ8w'},
 {'folder_name': 'forms_table',
  'file_name': '0001950972.csv',
  'path_display': '/Nizar/forms_table/0001950972.csv',
  'size_bytes': 3499,
  'server_modified': '2026-01-31T14:58:19',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ9A'},
 {'folder_name': 'forms_table',
  'file_name': '0001841077.csv',
  'path_display': '/Nizar/forms_table/0001841077.csv',
  'size_bytes': 5525,
  'server_modified': '2026-01-31T14:58:23',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ9Q'},
 {'folder_name': 'forms_table',
  'file_name': '0002055944.csv',
  'path_display': '/Nizar/forms_table/0002055944.csv',
  'size_bytes': 1439,
  'server_modified': '2026-01-31T14:58:26',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ9g'},
 {'folder_name': 'forms_table',
  'file_name': '0001483097.csv',
  'path_display': '/Nizar/forms_table/0001483097.csv',
  'size_bytes': 4805,
  'server_modified': '2026-01-31T14:58:32',
  'id': 'id:q8Gozjz1MYAAAAAAAAgE_w'},
 {'folder_name': 'forms_table',
  'file_name': '0001843587.csv',
  'path_display': '/Nizar/forms_table/0001843587.csv',
  'size_bytes': 5878,
  'server_modified': '2026-01-31T14:58:35',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ9w'},
 {'folder_name': 'forms_table',
  'file_name': '0002058194.csv',
  'path_display': '/Nizar/forms_table/0002058194.csv',
  'size_bytes': 1011,
  'server_modified': '2026-01-31T14:58:38',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFAA'},
 {'folder_name': 'forms_table',
  'file_name': '0000080835.csv',
  'path_display': '/Nizar/forms_table/0000080835.csv',
  'size_bytes': 17742,
  'server_modified': '2026-01-31T14:58:43',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFAQ'},
 {'folder_name': 'forms_table',
  'file_name': '0001873893.csv',
  'path_display': '/Nizar/forms_table/0001873893.csv',
  'size_bytes': 4533,
  'server_modified': '2026-01-31T14:58:46',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ-A'},
 {'folder_name': 'forms_table',
  'file_name': '0001845671.csv',
  'path_display': '/Nizar/forms_table/0001845671.csv',
  'size_bytes': 1553,
  'server_modified': '2026-01-31T14:58:50',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFAw'},
 {'folder_name': 'forms_table',
  'file_name': '0001802324.csv',
  'path_display': '/Nizar/forms_table/0001802324.csv',
  'size_bytes': 6289,
  'server_modified': '2026-01-31T14:58:53',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ-Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001507966.csv',
  'path_display': '/Nizar/forms_table/0001507966.csv',
  'size_bytes': 1391,
  'server_modified': '2026-01-31T14:58:56',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFBA'},
 {'folder_name': 'forms_table',
  'file_name': '0001476534.csv',
  'path_display': '/Nizar/forms_table/0001476534.csv',
  'size_bytes': 6496,
  'server_modified': '2026-01-31T14:59:00',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFBQ'},
 {'folder_name': 'forms_table',
  'file_name': '0000884315.csv',
  'path_display': '/Nizar/forms_table/0000884315.csv',
  'size_bytes': 2901,
  'server_modified': '2026-01-31T14:59:03',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFBg'},
 {'folder_name': 'forms_table',
  'file_name': '0001136287.csv',
  'path_display': '/Nizar/forms_table/0001136287.csv',
  'size_bytes': 2754,
  'server_modified': '2026-01-31T14:59:06',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFBw'},
 {'folder_name': 'forms_table',
  'file_name': '0001978521.csv',
  'path_display': '/Nizar/forms_table/0001978521.csv',
  'size_bytes': 3491,
  'server_modified': '2026-01-31T14:59:09',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ-g'},
 {'folder_name': 'forms_table',
  'file_name': '0001359371.csv',
  'path_display': '/Nizar/forms_table/0001359371.csv',
  'size_bytes': 11503,
  'server_modified': '2026-01-31T14:59:12',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFCA'},
 {'folder_name': 'forms_table',
  'file_name': '0001846943.csv',
  'path_display': '/Nizar/forms_table/0001846943.csv',
  'size_bytes': 3863,
  'server_modified': '2026-01-31T14:59:19',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFCQ'},
 {'folder_name': 'forms_table',
  'file_name': '0001421669.csv',
  'path_display': '/Nizar/forms_table/0001421669.csv',
  'size_bytes': 23946,
  'server_modified': '2026-01-31T14:59:26',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ_A'},
 {'folder_name': 'forms_table',
  'file_name': '0001808275.csv',
  'path_display': '/Nizar/forms_table/0001808275.csv',
  'size_bytes': 5326,
  'server_modified': '2026-01-31T14:59:32',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFCg'},
 {'folder_name': 'forms_table',
  'file_name': '0001163603.csv',
  'path_display': '/Nizar/forms_table/0001163603.csv',
  'size_bytes': 10683,
  'server_modified': '2026-01-31T14:59:35',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFCw'},
 {'folder_name': 'forms_table',
  'file_name': '0001388743.csv',
  'path_display': '/Nizar/forms_table/0001388743.csv',
  'size_bytes': 3022,
  'server_modified': '2026-01-31T14:59:38',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFDA'},
 {'folder_name': 'forms_table',
  'file_name': '0001539436.csv',
  'path_display': '/Nizar/forms_table/0001539436.csv',
  'size_bytes': 16344,
  'server_modified': '2026-01-31T14:59:42',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ_Q'},
 {'folder_name': 'forms_table',
  'file_name': '0001909739.csv',
  'path_display': '/Nizar/forms_table/0001909739.csv',
  'size_bytes': 3452,
  'server_modified': '2026-01-31T14:59:48',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ_g'},
 {'folder_name': 'forms_table',
  'file_name': '0001689637.csv',
  'path_display': '/Nizar/forms_table/0001689637.csv',
  'size_bytes': 9816,
  'server_modified': '2026-01-31T14:59:52',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFDQ'},
 {'folder_name': 'forms_table',
  'file_name': '0001831187.csv',
  'path_display': '/Nizar/forms_table/0001831187.csv',
  'size_bytes': 4454,
  'server_modified': '2026-01-31T14:59:56',
  'id': 'id:q8Gozjz1MYAAAAAAAAgZ_w'},
 {'folder_name': 'forms_table',
  'file_name': '0001473174.csv',
  'path_display': '/Nizar/forms_table/0001473174.csv',
  'size_bytes': 1314,
  'server_modified': '2026-01-31T14:59:59',
  'id': 'id:q8Gozjz1MYAAAAAAAAgFDg'},
 {'folder_name': 'forms_table',
  'file_name': '0001938268.csv',
  'path_display': '/Nizar/forms_table/0001938268.csv',
  'size_bytes': 1347,
  'server_modified': '2026-01-31T15:00:06',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaAQ'},
 {'folder_name': 'forms_table',
  'file_name': '0001840775.csv',
  'path_display': '/Nizar/forms_table/0001840775.csv',
  'size_bytes': 6006,
  'server_modified': '2026-01-31T15:00:09',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaAw'},
 {'folder_name': 'forms_table',
  'file_name': '0001840261.csv',
  'path_display': '/Nizar/forms_table/0001840261.csv',
  'size_bytes': 5756,
  'server_modified': '2026-01-31T15:00:13',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaBA'},
 {'folder_name': 'forms_table',
  'file_name': '0002056676.csv',
  'path_display': '/Nizar/forms_table/0002056676.csv',
  'size_bytes': 1662,
  'server_modified': '2026-01-31T15:00:16',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaBQ'},
 {'folder_name': 'forms_table',
  'file_name': '0001636974.csv',
  'path_display': '/Nizar/forms_table/0001636974.csv',
  'size_bytes': 6795,
  'server_modified': '2026-01-31T15:00:19',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaBg'},
 {'folder_name': 'forms_table',
  'file_name': '0001730242.csv',
  'path_display': '/Nizar/forms_table/0001730242.csv',
  'size_bytes': 7634,
  'server_modified': '2026-01-31T15:00:24',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaBw'},
 {'folder_name': 'forms_table',
  'file_name': '0001389567.csv',
  'path_display': '/Nizar/forms_table/0001389567.csv',
  'size_bytes': 6109,
  'server_modified': '2026-01-31T15:00:27',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaCA'},
 {'folder_name': 'forms_table',
  'file_name': '0001805589.csv',
  'path_display': '/Nizar/forms_table/0001805589.csv',
  'size_bytes': 5783,
  'server_modified': '2026-01-31T15:00:32',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaCQ'},
 {'folder_name': 'forms_table',
  'file_name': '0001799883.csv',
  'path_display': '/Nizar/forms_table/0001799883.csv',
  'size_bytes': 7146,
  'server_modified': '2026-01-31T15:00:36',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaCg'},
 {'folder_name': 'forms_table',
  'file_name': '0002039313.csv',
  'path_display': '/Nizar/forms_table/0002039313.csv',
  'size_bytes': 1412,
  'server_modified': '2026-01-31T15:00:40',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaCw'},
 {'folder_name': 'forms_table',
  'file_name': '0001911026.csv',
  'path_display': '/Nizar/forms_table/0001911026.csv',
  'size_bytes': 4411,
  'server_modified': '2026-01-31T15:00:44',
  'id': 'id:q8Gozjz1MYAAAAAAAAgaDA'},
 {'folder_name': 'forms_table',

In [2]:
all_cik_data = []
for d in os.listdir("cik_chunks"):
    if "update" in d:

        with open(f"cik_chunks/{d}", "r", encoding="utf-8") as f:
            data = json.load(f)
        all_cik_data += data

In [3]:
len(all_cik_data)

1171120

In [10]:
df_cik = pd.DataFrame(all_cik_data).drop_duplicates(subset="cik")

In [11]:
cik_13f = df_cik[df_cik['13f_rows'] > 0]

In [12]:
cik_13f['cik'].nunique()

18828

In [7]:
df = pd.read_csv("dropbox_parquet_list.csv")

df['cik'] = df['file_name'].map(lambda x: x.split('_')[0])
df

,folder_name,file_name,size_bytes,server_modified,path_display,id,cik
0,2009_12_31,0001463262_0001463262_10_000002_2009_12_31.par...,10843,2026-01-10T06:32:01,/sec_forms/2009_12_31/0001463262_0001463262_10...,id:6vCWYvjF-JAAAAAAAAAAFg,0001463262
1,2009_12_31,0001463262_0001463262_10_000001_2009_12_31.par...,17242,2026-01-10T06:32:07,/sec_forms/2009_12_31/0001463262_0001463262_10...,id:6vCWYvjF-JAAAAAAAAAAGQ,0001463262
2,2009_09_30,0001463262_0001463262_09_000006_2009_09_30.par...,16201,2026-01-10T06:32:12,/sec_forms/2009_09_30/0001463262_0001463262_09...,id:6vCWYvjF-JAAAAAAAAAAGg,0001463262
3,2009_06_30,0001463262_0001463262_09_000005_2009_06_30.par...,16485,2026-01-10T06:32:19,/sec_forms/2009_06_30/0001463262_0001463262_09...,id:6vCWYvjF-JAAAAAAAAAAHQ,0001463262
4,2009_03_31,0001463262_0001463262_09_000004_2009_03_31.par...,17074,2026-01-10T06:32:24,/sec_forms/2009_03_31/0001463262_0001463262_09...,id:6vCWYvjF-JAAAAAAAAAAHw,0001463262
...,...,...,...,...,...,...,...
453548,2017_12_31,0000949509_0000949509_18_000002_2017_12_31.par...,24241,2026-01-02T11:36:12,/Nizar/sec_forms/2017_12_31/0000949509_0000949...,id:q8Gozjz1MYAAAAAAAAgE9w,0000949509
453549,2017_12_31,0000945631_0000945631_18_000006_2017_12_31.par...,17781,2026-01-02T11:36:14,/Nizar/sec_forms/2017_12_31/0000945631_0000945...,id:q8Gozjz1MYAAAAAAAAgE-A,0000945631
453550,2017_12_31,0000944388_0001062993_18_000787_2017_12_31.par...,44847,2026-01-02T11:36:17,/Nizar/sec_forms/2017_12_31/0000944388_0001062...,id:q8Gozjz1MYAAAAAAAAgE-Q,0000944388
453551,2017_12_31,0000916542_0001140361_18_002328_2017_12_31.par...,82019,2026-01-02T11:36:19,/Nizar/sec_forms/2017_12_31/0000916542_0001140...,id:q8Gozjz1MYAAAAAAAAgE-g,0000916542
453552,2017_12_31,0000915191_0001104659_18_009307_2017_12_31.par...,17143,2026-01-02T11:36:21,/Nizar/sec_forms/2017_12_31/0000915191_0001104...,id:q8Gozjz1MYAAAAAAAAgE-w,0000915191

In [8]:
df['cik'].nunique()

13621

In [13]:
df.drop_duplicates(subset="file_name")

,folder_name,file_name,size_bytes,server_modified,path_display,id
0,2025_09_30,0000005272_0000005272_25_000152_2025_09_30.par...,14360,2025-11-14T11:38:11,/Nizar/sec_forms/2025_09_30/0000005272_0000005...,id:q8Gozjz1MYAAAAAAAAJPNg
1,2025_09_30,0000002230_0001104659_25_101562_2025_09_30.par...,18997,2025-11-14T11:38:12,/Nizar/sec_forms/2025_09_30/0000002230_0001104...,id:q8Gozjz1MYAAAAAAAAJPOA
2,2025_09_30,0000004962_0000004962_25_000236_2025_09_30.par...,14578,2025-11-14T11:38:12,/Nizar/sec_forms/2025_09_30/0000004962_0000004...,id:q8Gozjz1MYAAAAAAAAJPOQ
3,2025_09_30,0000004977_0001628280_25_049287_2025_09_30.par...,14601,2025-11-14T11:38:12,/Nizar/sec_forms/2025_09_30/0000004977_0001628...,id:q8Gozjz1MYAAAAAAAAJPOg
4,2025_09_30,0000007195_0000007195_25_000006_2025_09_30.par...,20065,2025-11-14T11:38:12,/Nizar/sec_forms/2025_09_30/0000007195_0000007...,id:q8Gozjz1MYAAAAAAAAJPOw
...,...,...,...,...,...,...
9070,2025_06_30,0001594591_0001594591_25_000004_2025_06_30.par...,14561,2025-12-14T07:55:26,/Nizar/sec_forms/2025_06_30/0001594591_0001594...,id:q8Gozjz1MYAAAAAAAAJ0og
9071,2025_06_30,0001594540_0001085146_25_003900_2025_06_30.par...,15036,2025-12-14T07:55:28,/Nizar/sec_forms/2025_06_30/0001594540_0001085...,id:q8Gozjz1MYAAAAAAAAJ0ow
9072,2025_06_30,0001594467_0001104659_25_069041_2025_06_30.par...,14471,2025-12-14T07:55:31,/Nizar/sec_forms/2025_06_30/0001594467_0001104...,id:q8Gozjz1MYAAAAAAAAJ0pA
9073,2025_06_30,0001594467_0001104659_25_068255_2025_06_30.par...,14471,2025-12-14T07:55:33,/Nizar/sec_forms/2025_06_30/0001594467_0001104...,id:q8Gozjz1MYAAAAAAAAJ0pQ
9074,2025_06_30,0001593688_0001593688_25_000004_2025_06_30.par...,18442,2025-12-14T07:55:35,/Nizar/sec_forms/2025_06_30/0001593688_0001593...,id:q8Gozjz1MYAAAAAAAAJ0pg

In [19]:
df_drive = pd.read_csv("drive_files.csv")
df_drive.columns

Index(['folder_name', 'file_name', 'cik', 'acsn', 'fid'], dtype='object')

In [21]:
df_drive[df_drive['folder_name']=='2025_06_30']

,folder_name,file_name,cik,acsn,fid
4639,2025_06_30,0001115419_0001420506_25_001859_2025_06_30.par...,1115419,0001420506-25-001859,11DZzwxBOdsfXBvKzhQr7OLFLe2aZq2Zg
4640,2025_06_30,0000936922_0000936922_25_000005_2025_06_30.par...,936922,0000936922-25-000005,110q-a7PAzenIs6AtLr6GcZICLNeMSKy5
4641,2025_06_30,0000052428_0000950123_25_008185_2025_06_30.par...,52428,0000950123-25-008185,1Mb0EQeuD2c4-cgkHPJviFboVBbiyna6h
4642,2025_06_30,0002076121_0002076121_25_000001_2025_06_30.par...,2076121,0002076121-25-000001,1RP4yyhePHR1-2QmYedn7CgbxEa0yDPJm
4643,2025_06_30,0001114634_0001167376_25_000009_2025_06_30.par...,1114634,0001167376-25-000009,1-ALtkc7tsSDtWOUqSk9Z16S07NFOsAHy
...,...,...,...,...,...
14291,2025_06_30,0000004977_0000004977_25_000136_2025_06_30.par...,4977,0000004977-25-000136,1mW8GS6_gfcPjJNUx2O3htbm5UZjk8Q3w
14292,2025_06_30,0000002230_0001104659_25_072132_2025_06_30.par...,2230,0001104659-25-072132,1_qsZWmkdVfbjrflFMShj_nzfVwTpseGk
14293,2025_06_30,0000914976_0001172661_25_003456_2025_06_30.par...,914976,0001172661-25-003456,1AF9pBWmDwPtc3hdr5kh5TncggC9dueL0
14294,2025_06_30,0001067983_0000950123_25_008343_2025_06_30.par...,1067983,0000950123-25-008343,1-n0QktmyqyNFllrFB_Y_LypMBnRol-WC
14295,2025_06_30,0000860643_0000860643_25_000004_2025_06_30.par...,860643,0000860643-25-000004,14bFzh34GgNKWmFlNx4ARaFcIrxRqJM2k